### ISSUE TITLE
split_words NameError

### ISSUE THREAD

**Issue by sh1457** [Shreesha-S/VTU-Results-Analysis#1]
```
Traceback (most recent call last):
  File "script.py", line 31, in <module>
    data_file.write(split_words[-6].split(" &")[0].split(" ")[1])
NameError: name 'split_words' is not defined
```

Got that error when I ran the script.
I successfully ran the script from 001 to 110, verified my own.
It's looking good.

**Comment by shreeshasuresh** [comment]
Can specify the steps to reproduce that error?

**Comment by sh1457** [comment]
Just ran the script.

**Comment by sh1457** [comment]
Could split_words be a reserved word by chance.

**Comment by shreeshasuresh** [comment]
No. It came up when the HTML response from the website was different from usual HTML page containing marks which comes up for a successful return. Working on it.

**Comment by sh1457** [comment]
I see
I was able to port it to bash

**Comment by sh1457** [comment]
```
([usn])
Semester:3
(10MAT31)442165P
(10CS32)5813F
(10CS33)181533F
(10CS34)371350P
(10CS35)38745F
(10CS36)251843F
(10CSL37)451863P
(10CSL38)151328F
Semester:2
(10EME24)271542F
42
```

**Comment by sh1457** [comment]
And I can Isolate subjects since lines start with subject code.

**Comment by shreeshasuresh** [comment]
Awesome! Try spacing the external, internal and total scores! It looks great!

**Comment by sh1457** [comment]
It takes around 30 secs to get 111 results and split it into subject wise files.
Yeah thats coming soon.
